// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.15.7
// source: follower.proto

package follower

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//2PC
type InputForSC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` //the called sc
	Input   []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`     //the input of the sc
	Txid    uint64 `protobuf:"varint,3,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (x *InputForSC) Reset() {
	*x = InputForSC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputForSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputForSC) ProtoMessage() {}

func (x *InputForSC) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputForSC.ProtoReflect.Descriptor instead.
func (*InputForSC) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{0}
}

func (x *InputForSC) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *InputForSC) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InputForSC) GetTxid() uint64 {
	if x != nil {
		return x.Txid
	}
	return 0
}

type ResultFromEVM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`        //return
	Issuccess bool   `protobuf:"varint,2,opt,name=issuccess,proto3" json:"issuccess,omitempty"` //Is the invocation successful
}

func (x *ResultFromEVM) Reset() {
	*x = ResultFromEVM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultFromEVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultFromEVM) ProtoMessage() {}

func (x *ResultFromEVM) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultFromEVM.ProtoReflect.Descriptor instead.
func (*ResultFromEVM) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{1}
}

func (x *ResultFromEVM) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResultFromEVM) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

type EVMResultFromVoter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Issuccess  bool   `protobuf:"varint,2,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	SignedData []byte `protobuf:"bytes,3,opt,name=signedData,proto3" json:"signedData,omitempty"`
}

func (x *EVMResultFromVoter) Reset() {
	*x = EVMResultFromVoter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EVMResultFromVoter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVMResultFromVoter) ProtoMessage() {}

func (x *EVMResultFromVoter) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVMResultFromVoter.ProtoReflect.Descriptor instead.
func (*EVMResultFromVoter) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{2}
}

func (x *EVMResultFromVoter) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *EVMResultFromVoter) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *EVMResultFromVoter) GetSignedData() []byte {
	if x != nil {
		return x.SignedData
	}
	return nil
}

type ProposeReqForSC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx []*Transaction `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
}

func (x *ProposeReqForSC) Reset() {
	*x = ProposeReqForSC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposeReqForSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeReqForSC) ProtoMessage() {}

func (x *ProposeReqForSC) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeReqForSC.ProtoReflect.Descriptor instead.
func (*ProposeReqForSC) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{3}
}

func (x *ProposeReqForSC) GetTx() []*Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type CommitReqForSC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx []*Transaction `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
}

func (x *CommitReqForSC) Reset() {
	*x = CommitReqForSC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitReqForSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReqForSC) ProtoMessage() {}

func (x *CommitReqForSC) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReqForSC.ProtoReflect.Descriptor instead.
func (*CommitReqForSC) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{4}
}

func (x *CommitReqForSC) GetTx() []*Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type ResponseFromFollower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
}

func (x *ResponseFromFollower) Reset() {
	*x = ResponseFromFollower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseFromFollower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFromFollower) ProtoMessage() {}

func (x *ResponseFromFollower) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFromFollower.ProtoReflect.Descriptor instead.
func (*ResponseFromFollower) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseFromFollower) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NumberOfAddress     uint64 `protobuf:"varint,2,opt,name=numberOfAddress,proto3" json:"numberOfAddress,omitempty"`
	AccessAddressList   []byte `protobuf:"bytes,3,opt,name=AccessAddressList,proto3" json:"AccessAddressList,omitempty"`
	Input               []byte `protobuf:"bytes,4,opt,name=Input,proto3" json:"Input,omitempty"`
	PositionOfCallChain uint64 `protobuf:"varint,5,opt,name=PositionOfCallChain,proto3" json:"PositionOfCallChain,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{6}
}

func (x *Transaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetNumberOfAddress() uint64 {
	if x != nil {
		return x.NumberOfAddress
	}
	return 0
}

func (x *Transaction) GetAccessAddressList() []byte {
	if x != nil {
		return x.AccessAddressList
	}
	return nil
}

func (x *Transaction) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Transaction) GetPositionOfCallChain() uint64 {
	if x != nil {
		return x.PositionOfCallChain
	}
	return 0
}

type ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Nodeaddr  []byte `protobuf:"bytes,2,opt,name=nodeaddr,proto3" json:"nodeaddr,omitempty"`
}

func (x *ACK) Reset() {
	*x = ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follower_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACK) ProtoMessage() {}

func (x *ACK) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACK.ProtoReflect.Descriptor instead.
func (*ACK) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{7}
}

func (x *ACK) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *ACK) GetNodeaddr() []byte {
	if x != nil {
		return x.Nodeaddr
	}
	return nil
}

var File_follower_proto protoreflect.FileDescriptor

var file_follower_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x46, 0x6f, 0x72, 0x53, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x45, 0x56, 0x4d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x6a, 0x0a, 0x12, 0x45, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x46, 0x6f, 0x72, 0x53, 0x43, 0x12,
	0x25, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x02, 0x74, 0x78, 0x22, 0x37, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x46, 0x6f, 0x72, 0x53, 0x43, 0x12, 0x25, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x78, 0x22,
	0x34, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x2c, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x66, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x13, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x66, 0x43, 0x61, 0x6c, 0x6c,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x3f, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x61, 0x64, 0x64, 0x72, 0x32, 0xb1, 0x02, 0x0a, 0x08, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x19, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x43,
	0x61, 0x6c, 0x6c, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x12, 0x14, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x46, 0x6f, 0x72, 0x53, 0x43, 0x1a, 0x17, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x45, 0x56, 0x4d, 0x12,
	0x41, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x3e, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x56, 0x0a, 0x20, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x43, 0x61,
	0x6c, 0x6c, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54,
	0x6f, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x53, 0x43, 0x1a, 0x1c, 0x2e, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x45, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x42, 0x14, 0x5a, 0x12, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_follower_proto_rawDescOnce sync.Once
	file_follower_proto_rawDescData = file_follower_proto_rawDesc
)

func file_follower_proto_rawDescGZIP() []byte {
	file_follower_proto_rawDescOnce.Do(func() {
		file_follower_proto_rawDescData = protoimpl.X.CompressGZIP(file_follower_proto_rawDescData)
	})
	return file_follower_proto_rawDescData
}

var file_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_follower_proto_goTypes = []interface{}{
	(*InputForSC)(nil),           // 0: follower.InputForSC
	(*ResultFromEVM)(nil),        // 1: follower.ResultFromEVM
	(*EVMResultFromVoter)(nil),   // 2: follower.EVMResultFromVoter
	(*ProposeReqForSC)(nil),      // 3: follower.ProposeReqForSC
	(*CommitReqForSC)(nil),       // 4: follower.CommitReqForSC
	(*ResponseFromFollower)(nil), // 5: follower.ResponseFromFollower
	(*Transaction)(nil),          // 6: follower.Transaction
	(*ACK)(nil),                  // 7: follower.ACK
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_follower_proto_depIdxs = []int32{
	6, // 0: follower.ProposeReqForSC.tx:type_name -> follower.Transaction
	6, // 1: follower.CommitReqForSC.tx:type_name -> follower.Transaction
	0, // 2: follower.Follower.InternalCallSmartContract:input_type -> follower.InputForSC
	6, // 3: follower.Follower.PreCommitRequest:input_type -> follower.Transaction
	6, // 4: follower.Follower.CommitRequest:input_type -> follower.Transaction
	0, // 5: follower.Follower.InternalCallSmartContractToVoter:input_type -> follower.InputForSC
	1, // 6: follower.Follower.InternalCallSmartContract:output_type -> follower.ResultFromEVM
	8, // 7: follower.Follower.PreCommitRequest:output_type -> google.protobuf.Empty
	8, // 8: follower.Follower.CommitRequest:output_type -> google.protobuf.Empty
	2, // 9: follower.Follower.InternalCallSmartContractToVoter:output_type -> follower.EVMResultFromVoter
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_follower_proto_init() }
func file_follower_proto_init() {
	if File_follower_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_follower_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputForSC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultFromEVM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EVMResultFromVoter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposeReqForSC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitReqForSC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseFromFollower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follower_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_follower_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follower_proto_goTypes,
		DependencyIndexes: file_follower_proto_depIdxs,
		MessageInfos:      file_follower_proto_msgTypes,
	}.Build()
	File_follower_proto = out.File
	file_follower_proto_rawDesc = nil
	file_follower_proto_goTypes = nil
	file_follower_proto_depIdxs = nil
}
