# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coordinator.proto',
  package='coordinator',
  syntax='proto3',
  serialized_options=b'Z\025committer/coordinator',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63oordinator.proto\x12\x0b\x63oordinator\x1a\x1bgoogle/protobuf/empty.proto\",\n\nInputForSC\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\r\n\x05input\x18\x02 \x01(\x0c\"2\n\rResultFromEVM\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x12\x11\n\tissuccess\x18\x02 \x01(\x08\"7\n\x0fProposeReqForSC\x12$\n\x02tx\x18\x01 \x03(\x0b\x32\x18.coordinator.Transaction\"6\n\x0e\x43ommitReqForSC\x12$\n\x02tx\x18\x01 \x03(\x0b\x32\x18.coordinator.Transaction\")\n\x14ResponseFromFollower\x12\x11\n\tissuccess\x18\x01 \x01(\x08\"y\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x17\n\x0fnumberOfAddress\x18\x02 \x01(\x04\x12\x19\n\x11\x41\x63\x63\x65ssAddressList\x18\x03 \x01(\x0c\x12\r\n\x05Input\x18\x04 \x01(\x0c\x12\x1b\n\x13positionOfCallChain\x18\x05 \x01(\x04\"U\n\x03\x41\x43K\x12\x11\n\tissuccess\x18\x01 \x01(\x08\x12\x10\n\x08nodeaddr\x18\x02 \x01(\x0c\x12\x0c\n\x04txid\x18\x03 \x01(\x04\x12\x1b\n\x13positionOfCallChain\x18\x04 \x01(\x04\x32\xd7\x01\n\x0b\x43oordinator\x12\x43\n\x0fSendTransaction\x12\x18.coordinator.Transaction\x1a\x16.google.protobuf.Empty\x12?\n\x13\x43ommitPhaseResponse\x12\x10.coordinator.ACK\x1a\x16.google.protobuf.Empty\x12\x42\n\x16PreCommitPhaseResponse\x12\x10.coordinator.ACK\x1a\x16.google.protobuf.EmptyB\x17Z\x15\x63ommitter/coordinatorb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_INPUTFORSC = _descriptor.Descriptor(
  name='InputForSC',
  full_name='coordinator.InputForSC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='coordinator.InputForSC.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input', full_name='coordinator.InputForSC.input', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=107,
)


_RESULTFROMEVM = _descriptor.Descriptor(
  name='ResultFromEVM',
  full_name='coordinator.ResultFromEVM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='coordinator.ResultFromEVM.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issuccess', full_name='coordinator.ResultFromEVM.issuccess', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=159,
)


_PROPOSEREQFORSC = _descriptor.Descriptor(
  name='ProposeReqForSC',
  full_name='coordinator.ProposeReqForSC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx', full_name='coordinator.ProposeReqForSC.tx', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=216,
)


_COMMITREQFORSC = _descriptor.Descriptor(
  name='CommitReqForSC',
  full_name='coordinator.CommitReqForSC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx', full_name='coordinator.CommitReqForSC.tx', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=272,
)


_RESPONSEFROMFOLLOWER = _descriptor.Descriptor(
  name='ResponseFromFollower',
  full_name='coordinator.ResponseFromFollower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuccess', full_name='coordinator.ResponseFromFollower.issuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=315,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='coordinator.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='coordinator.Transaction.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numberOfAddress', full_name='coordinator.Transaction.numberOfAddress', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AccessAddressList', full_name='coordinator.Transaction.AccessAddressList', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Input', full_name='coordinator.Transaction.Input', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positionOfCallChain', full_name='coordinator.Transaction.positionOfCallChain', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=438,
)


_ACK = _descriptor.Descriptor(
  name='ACK',
  full_name='coordinator.ACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuccess', full_name='coordinator.ACK.issuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodeaddr', full_name='coordinator.ACK.nodeaddr', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txid', full_name='coordinator.ACK.txid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positionOfCallChain', full_name='coordinator.ACK.positionOfCallChain', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=525,
)

_PROPOSEREQFORSC.fields_by_name['tx'].message_type = _TRANSACTION
_COMMITREQFORSC.fields_by_name['tx'].message_type = _TRANSACTION
DESCRIPTOR.message_types_by_name['InputForSC'] = _INPUTFORSC
DESCRIPTOR.message_types_by_name['ResultFromEVM'] = _RESULTFROMEVM
DESCRIPTOR.message_types_by_name['ProposeReqForSC'] = _PROPOSEREQFORSC
DESCRIPTOR.message_types_by_name['CommitReqForSC'] = _COMMITREQFORSC
DESCRIPTOR.message_types_by_name['ResponseFromFollower'] = _RESPONSEFROMFOLLOWER
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['ACK'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputForSC = _reflection.GeneratedProtocolMessageType('InputForSC', (_message.Message,), {
  'DESCRIPTOR' : _INPUTFORSC,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.InputForSC)
  })
_sym_db.RegisterMessage(InputForSC)

ResultFromEVM = _reflection.GeneratedProtocolMessageType('ResultFromEVM', (_message.Message,), {
  'DESCRIPTOR' : _RESULTFROMEVM,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.ResultFromEVM)
  })
_sym_db.RegisterMessage(ResultFromEVM)

ProposeReqForSC = _reflection.GeneratedProtocolMessageType('ProposeReqForSC', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSEREQFORSC,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.ProposeReqForSC)
  })
_sym_db.RegisterMessage(ProposeReqForSC)

CommitReqForSC = _reflection.GeneratedProtocolMessageType('CommitReqForSC', (_message.Message,), {
  'DESCRIPTOR' : _COMMITREQFORSC,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.CommitReqForSC)
  })
_sym_db.RegisterMessage(CommitReqForSC)

ResponseFromFollower = _reflection.GeneratedProtocolMessageType('ResponseFromFollower', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEFROMFOLLOWER,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.ResponseFromFollower)
  })
_sym_db.RegisterMessage(ResponseFromFollower)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

ACK = _reflection.GeneratedProtocolMessageType('ACK', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:coordinator.ACK)
  })
_sym_db.RegisterMessage(ACK)


DESCRIPTOR._options = None

_COORDINATOR = _descriptor.ServiceDescriptor(
  name='Coordinator',
  full_name='coordinator.Coordinator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=528,
  serialized_end=743,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendTransaction',
    full_name='coordinator.Coordinator.SendTransaction',
    index=0,
    containing_service=None,
    input_type=_TRANSACTION,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CommitPhaseResponse',
    full_name='coordinator.Coordinator.CommitPhaseResponse',
    index=1,
    containing_service=None,
    input_type=_ACK,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PreCommitPhaseResponse',
    full_name='coordinator.Coordinator.PreCommitPhaseResponse',
    index=2,
    containing_service=None,
    input_type=_ACK,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATOR)

DESCRIPTOR.services_by_name['Coordinator'] = _COORDINATOR

# @@protoc_insertion_point(module_scope)
